apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: web
  namespace: default
spec:
  gatewayClassName: envoy-gateway-class
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: app.local.test
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: app-tls
